### Creates a new event
POST localhost:8080/events
Content-Type: application/json

{
  "name": "Festa do TI",
  "startDate": "2024-01-22",
  "endDate": "2024-01-23",
  "institutionId": "9d65ab9d-2485-4979-b72d-cf3595dad761"
}

### Gets an event by Id
GET localhost:8080/events/9dafdb02-e824-4f71-8277-2422bec5e9c1
Accept: application/json

### Gets all events
GET localhost:8080/events
Accept: application/json

### Updates an event
PUT localhost:8080/events/1c8a7604-819b-41a1-92e3-c1568a49e8ea
Content-Type: application/json

{
  "name": "Test Daniel",
  "startDate": "2024-05-01T00:00:00.000Z",
  "endDate": "2024-05-02T00:00:00.000Z",
  "institutionId": "5fb7944d-a29e-4b30-8e20-aed2ffd9d954"
}

### Deletes an event
DELETE localhost:8080/events/04ba736b-b90c-453e-9bf0-85e40a247079
