### Creates a new event
POST localhost:8080/events
Content-Type: application/json

{
  "name": "Lançamento de Resultados 2024",
  "startDate": "2024-01-21",
  "endDate": "2024-01-22",
  "institutionId": "9d65ab9d-2485-4979-b72d-cf3595dad761"
}

### Gets an event by Id
GET localhost:8080/events/9dafdb02-e824-4f71-8277-2422bec5e9c1
Accept: application/json

### Gets all events
GET localhost:8080/events
Accept: application/json

### Updates an event
PUT localhost:8080/events/04ba736b-b90c-453e-9bf0-85e40a247079
Content-Type: application/json

{
  "name": "Demonstracao de Resultados 2026",
  "startDate": "2026-02-01",
  "endDate": "2026-02-02",
  "institutionId": "78177c74-82dd-4b1e-86a2-8a5cde156cc1"
}

### Deletes an event
DELETE localhost:8080/events/04ba736b-b90c-453e-9bf0-85e40a247079
