### Creates a new institution
POST localhost:8080/institutions
Content-Type: application/json

{
  "name": "Cyclic Bank Inc.",
  "type": "CENTRAL"
}

### Gets an institution by id
GET localhost:8080/institutions/c2498ab9-fb33-4a36-92d8-f1ff537f0cdc
Accept: application/json

### Gets all institutions
GET localhost:8080/institutions
Accept: application/json


### Updates an institution
PUT localhost:8080/institutions/c2498ab9-fb33-4a36-92d8-f1ff537f0cdc
Content-Type: application/json

{
  "name": "Cyclic Bank Inc.",
  "type": "SINGULAR"
}


### Deletes an institution
DELETE localhost:8080/institutions/c2498ab9-fb33-4a36-92d8-f1ff537f0cdc
Accept: application/json