### Creates a new institution
POST localhost:8080/institutions
Content-Type: application/json

{
  "name": "Neo Bank Unlimited 123",
  "type": "CENTRAL"
}

### Gets an institution by id
GET localhost:8080/institutions/317e5866-e0b3-489e-828b-f08d4d9b2399
Accept: application/json

### Gets all institutions
GET localhost:8080/institutions
Accept: application/json


### Updates an institution
PUT localhost:8080/institutions/018f5469-918e-45c8-840f-1b6ecb896cd8
Content-Type: application/json

{
  "name": "Neo Bank Unlimited",
  "type": "SINGULAR"
}


### Deletes an institution
DELETE localhost:8080/institutions/018f5469-918e-45c8-840f-1b6ecb896cd8
Accept: application/json